### ISSUE TITLE
Black Screen Loading and Flickering Logo

### ISSUE THREAD

**Issue by ArcadEd** [ludei/Construct-2-plugin#23]
I'm not sure if this is C2 specific, or if it's cloud compiler specific.  

Is there anything can be done with either issue.

1.  When you first launch a project on mobile device you get a black screen.  Depending on big the game is, this screen can be shown for up to 15 seconds.  Then the Ludei Logo.  Is there anything that can be done about that?  Even when I throw in a custom splash screen, it doesn't show until after the 15 seconds of blackness.  So many users just think the game as crashed and exit out.  Then leave bad reviews about the game not even launching.

2.  I know the flickering Ludei Logo has been discussed about a billion times.  Is there a fix in site for that?  Even changing the logo to show a LOADING.... text would be helpful I think.

**Comment by LibelulaV** [comment]
According to this link: http://support.ludei.com/hc/communities/public/questions/201895139-Construct2-Loader-Layout-Loadingprogress-not-work-anymore?page=1#answer-200661999
It is already possible to create a loading bar in C2 that works if you disable the lazy loading. 

Regards.
