### ISSUE TITLE
ShowFullscreen action runtime error

### ISSUE THREAD

**Issue by suntemple** [ludei/Construct-2-plugin#27]
There is an undeclared variable used in Acts.prototype.ShowFullscreen:

preloadingFullscreen = false;

This causes runtime error when trying to show full screen ads. 

In previous versions of the plugin it was declared and referenced in various locations. Now this line is the only place where it is left. Removing this line fixes everything.

**Comment by LibelulaV** [comment]
This was fixed long ago and I don't know why it is still open.
Thanks for reporting :). 

Regards.
