### ISSUE TITLE
Ads are overlapping the game content

### ISSUE THREAD

**Issue by AndreasReitberger** [ludei/Construct-2-plugin#42]
I know this isn't a bug, but it would be great to show the ads under the game content like on that screen shot. Otherwise the ads are really disturbing in the game.

AdMob (native) Plugin for Crosswalk

![levicat_ads](https://cloud.githubusercontent.com/assets/2952443/4779661/06ccd630-5c3e-11e4-8ffe-ddc818044cda.png)

CocoonJS Plugin

![ludei_ads](https://cloud.githubusercontent.com/assets/2952443/4779663/0ea082c6-5c3e-11e4-8881-e9fb84f67797.png)

Also the latest SDK of admob supports more sizes of the banners. Do you consider to add this feature too?

![image](https://cloud.githubusercontent.com/assets/2952443/4779665/372d994a-5c3e-11e4-9694-9484f064e705.png)

Thanks @ludei

**Comment by LibelulaV** [comment]
There is a new plugin for ads. It is not available at the cloud yet, just cordova exportations and Webview+ for cordova. But what you asked is supported. 

https://github.com/ludei/atomic-plugins-c2

Regards.
