### ISSUE TITLE
Latest Android build of game crashes

### ISSUE THREAD

**Issue by MichaelVParent** [ludei/Construct-2-plugin#59]
Hi,

After my hand-made loading screen, just as my game enters the main menu, the game crashes.  Here's the log: 
Console::Log line 102: Updated namespace: - Cocoon.Multiplayer
I/IDTKLog ( 5620): IDTK_LOG_INFO: [JS] Invoked in JSValueRef ludei::js::core::JS
Console::Log line 102: Updated namespace: - Cocoon.Multiplayer
I/IDTKLog ( 5620): IDTK_LOG_INFO: [JS] Invoked in JSValueRef ludei::js::core::JS
Console::Log line 102: Updated namespace: - Cocoon.Multiplayer
I/IDTKLog ( 5620): IDTK_LOG_INFO: [JS] Invoked in JSValueRef ludei::js::core::JS
Console::Log line 102: The CocoonJS binding for Box2D has been ignored because e
xt.IDTK_SRV_BOX2D is not available
W/IDTKLog ( 5620): IDTK_LOG_WARNING: [JS] Invoked in JSValueRef ludei::js::core:
:JSDocument::GetElementById line 229:  Not found getElementById: c2canvasdiv
D/dalvikvm( 5620): GC_CONCURRENT freed 3597K, 34% free 10198K/15367K, paused 11m
s+2ms, total 34ms
D/dalvikvm( 5620): WAIT_FOR_CONCURRENT_GC blocked 3ms
D/dalvikvm( 5620): GC_FOR_ALLOC freed 550K, 31% free 10709K/15367K, paused 15ms,
 total 15ms
D/dalvikvm( 5620): GC_FOR_ALLOC freed 2221K, 41% free 9195K/15367K, paused 14ms,
 total 14ms
I/dalvikvm-heap( 5620): Grow heap (frag case) to 10.399MB for 1449304-byte alloc
ation
D/dalvikvm( 5620): GC_CONCURRENT freed 0K, 31% free 10611K/15367K, paused 12ms+1
ms, total 22ms
D/dalvikvm( 5620): GC_FOR_ALLOC freed 1415K, 36% free 9903K/15367K, paused 15ms,
 total 15ms
I/dalvikvm-heap( 5620): Grow heap (frag case) to 12.472MB for 2898592-byte alloc
ation
D/dalvikvm( 5620): GC_CONCURRENT freed 0K, 18% free 12734K/15367K, paused 11ms+2
ms, total 23ms
D/dalvikvm( 5620): WAIT_FOR_CONCURRENT_GC blocked 1ms
D/dalvikvm( 5620): GC_FOR_ALLOC freed 0K, 18% free 12734K/15367K, paused 11ms, t
otal 11ms
I/dalvikvm-heap( 5620): Grow heap (frag case) to 13.854MB for 1449304-byte alloc
ation
D/dalvikvm( 5620): GC_FOR_ALLOC freed 2830K, 33% free 11318K/16839K, paused 15ms
, total 15ms
D/dalvikvm( 5620): GC_FOR_ALLOC freed <1K, 33% free 11318K/16839K, paused 14ms,
total 14ms
I/dalvikvm-heap( 5620): Grow heap (frag case) to 13.163MB for 2173240-byte alloc
ation
D/dalvikvm( 5620): GC_CONCURRENT freed 0K, 21% free 13441K/16839K, paused 12ms+2
ms, total 24ms
D/dalvikvm( 5620): WAIT_FOR_CONCURRENT_GC blocked 4ms
D/dalvikvm( 5620): GC_FOR_ALLOC freed 2830K, 37% free 10610K/16839K, paused 12ms
, total 12ms
I/dalvikvm-heap( 5620): Grow heap (frag case) to 12.470MB for 2173240-byte alloc
ation
D/dalvikvm( 5620): GC_CONCURRENT freed 0K, 25% free 12732K/16839K, paused 11ms+1
ms, total 25ms
D/dalvikvm( 5620): WAIT_FOR_CONCURRENT_GC blocked 7ms
I/IDTKLog ( 5620): IDTK_LOG_INFO: [JS] Invoked in JSValueRef ludei::js::core::JS
Console::Log line 102: [Construct 2] Letterbox scale fullscreen modes are not su
pported on this platform - falling back to 'Scale outer'
I/IDTKLog ( 5620): IDTK_LOG_INFO: [JS] Invoked in JSValueRef ludei::js::core::JS
Console::Log line 102: GooglePlayGames selected as social service
I/dalvikvm( 5620): Could not find method android.view.View.getDisplay, reference
d from method com.google.android.gms.games.internal.PopupManager$PopupManagerHCM
R1.m
W/dalvikvm( 5620): VFY: unable to resolve virtual method 8250: Landroid/view/Vie
w;.getDisplay ()Landroid/view/Display;
D/dalvikvm( 5620): VFY: replacing opcode 0x6e at 0x0009
W/PopupManager( 5620): You have not specified a View to use as content view for
popups. Falling back to the Activity content view which may not work properly in
 future versions of the API. Use setViewForPopups() to set your content view.
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture fadeinn-sheet0.png
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture clouds-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture sprite4-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture title-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture loading-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture dots-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture loggingin-sheet1.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture loggingin-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture copyright-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture topblack-sheet0.png
D/MoPub   ( 5620): Failed to retrieve GPS location: access appears to be disable
d.
D/MoPub   ( 5620): Failed to retrieve GPS location: access appears to be disable
d.
D/MoPub   ( 5620): Loading url: http://ads.mopub.com/m/ad?v=6&id=c98c18d7bc2344a
d9d973da3597fc6ad&nv=3.1.0&dn=MID%2CS7300B%2Csoftwin&udid=ifa%3Afbfaa955-0474-4a
df-8dfd-93f230ac23d0&z=%2B0200&o=p&sc_a=1.0&mr=1&ct=2&av=0.3&android_perms_ext_s
torage=1
I/MoPub   ( 5620): Fetching ad for task #0
I/com.mopub( 5620): Fetching ad for task #0
D/MoPub   ( 5620): Failed to retrieve GPS location: access appears to be disable
d.
D/MoPub   ( 5620): Failed to retrieve GPS location: access appears to be disable
d.
D/MoPub   ( 5620): Loading url: http://ads.mopub.com/m/ad?v=6&id=c98c18d7bc2344a
d9d973da3597fc6ad&nv=3.1.0&dn=MID%2CS7300B%2Csoftwin&udid=ifa%3Afbfaa955-0474-4a
df-8dfd-93f230ac23d0&z=%2B0200&o=p&sc_a=1.0&mr=1&ct=2&av=0.3&android_perms_ext_s
torage=1
I/MoPub   ( 5620): Already loading an ad for c98c18d7bc2344ad9d973da3597fc6ad, w
ait to finish.
I/com.mopub( 5620): Already loading an ad for c98c18d7bc2344ad9d973da3597fc6ad,
wait to finish.
D/MoPub   ( 5620): Ad Unit (c98c18d7bc2344ad9d973da3597fc6ad) is still warming u
p. Please try again in a few minutes.
I/MoPub   ( 5620): Ad failed to load.
I/com.mopub( 5620): Ad failed to load.
I/AndroidMoPubAdFullScreen( 5620): MoPub interstitial failed to load ad
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture sky_4.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture sunbg-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture sunface-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture hillsprite-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture hills2.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture wavetile.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture wavessprite-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture coconuttree_0-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture coconuttree_0-sheet1.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture hoppingcoconut-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture treenut-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture treenut-sheet1.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture tiledbackground3.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture ground_tile.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture camera-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture looper-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture ground_3.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture node2-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture node3-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture node4-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture node5-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture node1-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture groundsprite-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture ratebutton-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture mutebutton-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture gamecentericon-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture gamecentericon-sheet1.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture tutorialtoggle-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture tutorialtoggle-sheet1.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture tut_on-sheet0.png
I/IDTKLog ( 5620): IDTK_LOG_INFO: [IDTK] Invoked in ludei::js::WebKitTexture::re
loadTextureFromSrc line 431: Reloading texture tut_off-sheet0.png
D/AndroidRuntime( 5620): Shutting down VM
W/dalvikvm( 5620): threadid=1: thread exiting with uncaught exception (group=0x4
1b3c2a0)
E/AndroidRuntime( 5620): FATAL EXCEPTION: main
E/AndroidRuntime( 5620): java.lang.SecurityException: Provider gps requires ACCE
SS_FINE_LOCATION permission
E/AndroidRuntime( 5620):        at android.os.Parcel.readException(Parcel.java:1
425)
E/AndroidRuntime( 5620):        at android.os.Parcel.readException(Parcel.java:1
379)
E/AndroidRuntime( 5620):        at android.location.ILocationManager$Stub$Proxy.
getLastKnownLocation(ILocationManager.java:896)
E/AndroidRuntime( 5620):        at android.location.LocationManager.getLastKnown
Location(LocationManager.java:1168)
E/AndroidRuntime( 5620):        at com.ideateca.core.util.LocationManager$1.run(
LocationManager.java:133)
E/AndroidRuntime( 5620):        at android.os.Handler.handleCallback(Handler.jav
a:615)
E/AndroidRuntime( 5620):        at android.os.Handler.dispatchMessage(Handler.ja
va:92)
E/AndroidRuntime( 5620):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 5620):        at android.app.ActivityThread.main(ActivityThrea
d.java:4745)
E/AndroidRuntime( 5620):        at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime( 5620):        at java.lang.reflect.Method.invoke(Method.java:5
11)
E/AndroidRuntime( 5620):        at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 5620):        at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:553)
E/AndroidRuntime( 5620):        at dalvik.system.NativeStart.main(Native Method)

W/ActivityManager( 3592):   Force finishing activity com.RKadeGaming.jumpanzi/.J
umpanziActivity
I/InputReader( 3592): Reconfiguring input devices.  changes=0x00000004
I/InputReader( 3592): Device reconfigured: id=2, name='gt813_827_828', surface s
ize is now 1024x600, mode is 1
I/InputReader( 3592): Device reconfigured: id=6, name='adc joystick', surface si
ze is now 1024x600, mode is 1
I/ActivityManager( 3592): Config changed: {1.0 0mcc0mnc en_US sw600dp w1024dp h5
52dp lrg land finger -keyb/v/h -nav/h s.14}
D/dalvikvm( 3847): GC_CONCURRENT freed 540K, 10% free 6344K/6983K, paused 2ms+11
ms, total 222ms
W/ActivityManager( 3592): Activity pause timeout for ActivityRecord{425ca540 com
.RKadeGaming.jumpanzi/.JumpanziActivity}
I/Laucher ( 3816): -----Laucher is onRestart------
I/Launcher( 3816): -------command key_enable2.sh----------
I/System.out( 3816): ----------------------- print param: ----------------------
----
D/MyBroadcastReceiver( 3816): exec : ----------------------- print param: ------
--------------------
I/System.out( 3816): ----------------------- print param: ----------------------
----
D/MyBroadcastReceiver( 3816): exec : ----------------------- print param: ------
--------------------
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/Process ( 5620): Sending signal. PID: 5620 SIG: 9
W/InputDispatcher( 3592): channel '4238e310 com.RKadeGaming.jumpanzi/com.RKadeGa
ming.jumpanzi.JumpanziActivity (server)' ~ Consumer closed input channel or an e
rror occurred.  events=0x9
E/InputDispatcher( 3592): channel '4238e310 com.RKadeGaming.jumpanzi/com.RKadeGa
ming.jumpanzi.JumpanziActivity (server)' ~ Channel is unrecoverably broken and w
ill be disposed!
W/InputDispatcher( 3592): Attempted to unregister already unregistered input cha
nnel '4238e310 com.RKadeGaming.jumpanzi/com.RKadeGaming.jumpanzi.JumpanziActivit
y (server)'
I/WindowManager( 3592): WINDOW DIED Window{4238e310 com.RKadeGaming.jumpanzi/com
.RKadeGaming.jumpanzi.JumpanziActivity paused=false}
W/WindowManager( 3592): Force-removing child win Window{425775a0 SurfaceView pau
sed=false} from container Window{4238e310 com.RKadeGaming.jumpanzi/com.RKadeGami
ng.jumpanzi.JumpanziActivity paused=false}
W/AudioService( 3592):   AudioFocus   audio focus client died
I/AudioService( 3592):  AudioFocus  abandonAudioFocus(): removing entry for andr
oid.media.AudioManager@42150a08com.ideateca.core.framework.SystemInfo$1@42183b40

I/ActivityManager( 3592): Process com.RKadeGaming.jumpanzi (pid 5620) has died.
W/WindowManager( 3592): Failed looking up window
W/WindowManager( 3592): java.lang.IllegalArgumentException: Requested window and
roid.os.BinderProxy@424329f8 does not exist
W/WindowManager( 3592):         at com.android.server.wm.WindowManagerService.wi
ndowForClientLocked(WindowManagerService.java:7698)
W/WindowManager( 3592):         at com.android.server.wm.WindowManagerService.wi
ndowForClientLocked(WindowManagerService.java:7689)
W/WindowManager( 3592):         at com.android.server.wm.WindowState$DeathRecipi
ent.binderDied(WindowState.java:854)
W/WindowManager( 3592):         at android.os.BinderProxy.sendDeathNotice(Binder
.java:449)
W/WindowManager( 3592):         at dalvik.system.NativeStart.run(Native Method)
I/WindowState( 3592): WIN DEATH: null
W/WindowManager( 3592): Failed looking up window
W/WindowManager( 3592): java.lang.IllegalArgumentException: Requested window and
roid.os.BinderProxy@42496798 does not exist
W/WindowManager( 3592):         at com.android.server.wm.WindowManagerService.wi
ndowForClientLocked(WindowManagerService.java:7698)
W/WindowManager( 3592):         at com.android.server.wm.WindowManagerService.wi
ndowForClientLocked(WindowManagerService.java:7689)
W/WindowManager( 3592):         at com.android.server.wm.WindowState$DeathRecipi
ent.binderDied(WindowState.java:854)
W/WindowManager( 3592):         at android.os.BinderProxy.sendDeathNotice(Binder
.java:449)
W/WindowManager( 3592):         at dalvik.system.NativeStart.run(Native Method)
I/WindowState( 3592): WIN DEATH: null
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
D/dalvikvm( 3592): WAIT_FOR_CONCURRENT_GC blocked 0ms
W/JavaBinder( 3592): Binder has been finalized when calling linkToDeath() with r
ecip=0x1da00005)
D/dalvikvm( 3592): GC_EXPLICIT freed 314K, 30% free 11859K/16711K, paused 2ms+5m
s, total 69ms
D/audio_hw_primary( 2489): out_standby(0x400d46c0)
D/audio_hw_primary( 2489): do_output_standby(0x400d46c0)
V/audio_hw_primary( 2489): ~~~~ do_output_standby()....  call pcm_close()
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
W/ActivityManager( 3592): Activity destroy timeout for ActivityRecord{425ca540 c
om.RKadeGaming.jumpanzi/.JumpanziActivity}
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL
I/wpa_supplicant( 4075): [CTRL_IFACE]wlan0: SIGNAL_POLL

C:\androidsdk\sdk\platform-tools>

Any ideas?
Thanks,
Mike

**Comment by LibelulaV** [comment]
Hello, 

It seems you are asking a GPS location but you didn't ask for that permission at the cloud compiler. Please, be sure that you select the permission at the end of the configuration menu and click the blue button. 

Regards.

**Comment by MichaelVParent** [comment]
Thanks. That fixed it.
