### ISSUE TITLE
No app analytics support with cocoonjsads plugin?

### ISSUE THREAD

**Issue by MichaelVParent** [ludei/Construct-2-plugin#60]
Hi,

I had added a small amount of app analytics to to my game using the flurry plug-in.  Sadly this is not compatible with cocoonjs export of C2 made games. I was forced to remove the analytics.  Ludei cloud compile has settings for analytics, but I can find no reference to analytics in the plug-in.
Am I missing something?

Thanks,
Mike

**Comment by LibelulaV** [comment]
Hello, 

They are different things. The cloud's dashboard detects when your app is opened or closed, that kind of events. But we don't have a plugin for analytics right now. It is in our plans to create atomic plugins for analytics and we will adapt that plugin for C2. 
Here is the repository where we will upload them: https://github.com/ludei/atomic-plugins-c2

Regards.
