### ISSUE TITLE
App crashes on Android 4.0.4 after installing latest version of plugin manually

### ISSUE THREAD

**Issue by Christian1984** [ludei/Construct-2-plugin#63]
I have installed the latest version of the plugin as described in the repo's readme. However, when I export the demo project (or any other project exported with the plugin in place) and run it with the launcher app on my Samsung Galaxy Tablet with Android 4.0.4 the app crashes with the error shown in the screenshot below.
On iPad Air 2 with iOS 8.x it runs great! 

After restoring to the plugin version delivered with the latest built from Scirra, projects exported work fine (except for the fact that the demo app of course cannot be loaded, since the plugin is "outdated"). 

Any thoughts?

![screenshot_2015-03-13-11-36-46](https://cloud.githubusercontent.com/assets/5574632/6636866/5588cc9a-c974-11e4-94ea-8227986f3259.jpg)

**Comment by LibelulaV** [comment]
Hello, 

Are you sure you updated the prelude too? That function is included there. Which C2 version are you currently using? And is that the latest launcher? This error does not make sense unless you are using a very old Canvas+ version. Please, check that everything is up to date. 

If updating everything does not work, please, provide us a testcase, and I will try to reproduce the error under the same conditions. 

Regards.

**Comment by Christian1984** [comment]
Long story short: Upgrading the launcher did the trick! Thank you so much for the quick response and pointing out that really stupid mistake :-) Sometimes "did you try turning it off an on again?"-like hints really work! :-)
