### ISSUE TITLE
I emailed Ludei a month ago regarding upgrading my account to remove the Ludei loading screen and never got an answer

### ISSUE THREAD

**Issue by MichaelVParent** [ludei/Construct-2-plugin#67]
Can you contact me please at mike@brashmonkey.com to discuss the matter please?

I'd try another email, but it feels like I'm just sending them into a black hole. :(

Thanks,
Mike

**Comment by LibelulaV** [comment]
Hello, 

I will contact personally to the sales team in order to check how the state of your request is. Sorry for the inconveniences caused. 

Regards.

**Comment by MichaelVParent** [comment]
Still nothing. Please have them email me at mike@brashmonkey.com

Thanks LibelulaV

**Comment by MichaelVParent** [comment]
resolved. thanks LibelilaV.  I hope Ludei are paying you handsomely, you seem sometimes to be the only existing member of Ludei.

Cheers,
Mike
